baseurl = "https://Skanyi.github.io/blog/"
DefaultContentLanguage = "en"
title = "Kanyi Blog"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
disqusShortname = "kanyi"

[Params]
  subtitle = "Build Automate Secure"
  logo = "img/me.jpg"
  favicon = "img/avatar-icon.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true

[Author]
  name = "Stephen Kanyi"
  email = "tokanyi@gmail.com"
  github = "andela-skanyi"
  twitter = "StephenKanyiW"

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "DevOps"
    url = "devops/"
    weight = 2

[[menu.main]]
    name = "Security"
    url = "cyber-security/"
    weight = 2

[[menu.main]]
    name = "Development"
    url = "development/"
    weight = 2
